# buildspec for deploying latest changes to main development branch
version: 0.2
env:
  parameter-store:
    BRAINTREE_TOKEN: "/pwa/BRAINTREE_TOKEN"
    MAGENTO_BACKEND_URL: "/pwa/MAGENTO_BACKEND_URL"
phases:
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - echo copying env vars to env file
      - sed -i "s%MAGENTO_BACKEND_URL=redacted%MAGENTO_BACKEND_URL=${MAGENTO_BACKEND_URL}%g" ./docker/.env.docker.prod
      - sed -i "s/BRAINTREE_TOKEN=redacted/BRAINTREE_TOKEN=${BRAINTREE_TOKEN}/g" ./docker/.env.docker.prod
      - VERSION=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo VERSION=$VERSION
  build:
    commands:
      - echo build Docker image on `date`
      - docker build -f Dockerfile.prod -t pwa-demo:latest .
      - docker tag pwa-demo:latest 276375911640.dkr.ecr.us-east-1.amazonaws.com/pwa-demo:latest
      - docker tag pwa-demo:latest 276375911640.dkr.ecr.us-east-1.amazonaws.com/pwa-demo:$VERSION
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push 276375911640.dkr.ecr.us-east-1.amazonaws.com/pwa-demo:latest
      - docker push 276375911640.dkr.ecr.us-east-1.amazonaws.com/pwa-demo:$VERSION
      - sed -i "s/:latest/:${VERSION}/g" Dockerrun.aws.json
artifacts:
  files:
    - Dockerrun.aws.json
